<div class="container">
	<div id="ajax-home">
		<!--Affichage de l'ajax ici-->
		<?php require 'apps/contents/chat.php'; ?>
	</div>
	<div>
		<form method="POST">
			<div>
				<label for="user">User</label>
				<input id="user" type="text" name='user' value="<?=$user?>">
			</div>

			<div>
				<label for="message">message</label>
				<input id="message" type="text" name='message'>
				<input type="submit" value="Envoyer">
			</div>
		</form>
	</div>
</div>

<!--Ajax-->
<script>
	$(document).ready(function()
	{
		$('form').submit(function(info)
		{
			info.preventDefault();


			var $form = $(this),
				user = $form.find("input[name='user']").val(),
				message = $form.find("input[name='message']").val();


			if ($form.find("input[name='user']").val() == '')
				alert('Missing parameter : user');
			if ($form.find("input[name='message']").val() == '')
				alert('Missing parameter : message');

			$.post('index.php?page=home', {'user': user,'message': message }, function()
			{
  				$form.find("input[name='message']").val('').focus();
			});
			return false;
		});
		setInterval(function()
		{
			$("#ajax-home").load("index.php?page=chat&ajax");
		}, 1000);
	});
</script>