<div class="container">
	<div id="ajax-home">
		<!--Affichage de l'ajax ici-->
	</div>

	<div>
		<form method="POST">
			<div>
				<label for="user"></label>
				<input id="user" type="text" name="user">
			</div>

			<div>
				<label for="message"></label>
				<input id="message" type="text" name="message">
				<button id="envoyer" data-taget="selecteur" data-element="selecteur">Envoyer</button>
			</div>
		</form>
	</div>
</div>

<!--Ajax-->
<script>
	$(document).ready(function){
		$("#envoyer").click(function(){
			var target = $(this).data("target");
			var element = $(this).data("element");

			$("#ajax-home").load("index.php?page="+target+" "+element);
		});
	});
</script>